url: https://blog.turtlecoin.com

name: TurtleCoin® Blog
description: TurtleCoin® is a decentralized Peer-2-Peer Open Source electronic currency. It's easy to get, completely private and ready for you today.
author: TurtleCoin

permalink: /:title/
version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-json-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
